version: '3'
services:
  postgres:
    container_name: quest_bot_postgres
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - quest_bot
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  bot:
    container_name: quest_bot
    build: .
    networks:
      - quest_bot
    depends_on:
      - postgres

networks:
  quest_bot: